language: rust
rust:
  - stable
  - beta
jobs:
  fast_finish: true
cache: cargo
before_cache:
  - rm -rfv "$TRAVIS_HOME/.cargo/registry/src"
  - rm -rfv target/debug/incremental/flodgatt-*
  - rm -rfv target/debug/.fingerprint/flodgatt-*
  - rm -rfv target/debug/build/flodgatt-*
  - rm -rfv target/debug/deps/libflodgatt-*
  - rm -rfv target/debug/deps/flodgatt-*
  - rm -rfv target/debug/{flodgatt,libflodgatt}.d
  - cargo clean -p flodgatt
branches:
  only:
    - master
